LPS-170942 | master
liferay-appsec/liferay-portal pull request #1121
Opened 2023-05-17 02:49 UTC by JessieZhao0714

https://issues.liferay.com/browse/LPS-170942

2023-05-17 02:49 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**security**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-05-17 02:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11521/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11521/jenkins-report.html">here</a>.</b></p>

2023-05-17 02:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11522/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11522/jenkins-report.html">here</a>.</b></p>

2023-05-17 02:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/6750/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6750/jenkins-report.html">here</a>.</b></p>

2023-05-17 02:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2f1bffccccf0a0748f98ea94ea72429934ea8d3">e2f1bffccccf0a0748f98ea94ea72429934ea8d3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JessieZhao0714/liferay-portal/tree/master-qa-170942">master-qa-170942</a><br/>Branch GIT ID: <a href="https://github.com/JessieZhao0714/liferay-portal/commit/d3db8b842a4aa6efe33b101770ef9d98dbbedb1a">d3db8b842a4aa6efe33b101770ef9d98dbbedb1a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6750/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6750/jenkins-report.html">here</a>.</h5></details></html>

2023-05-17 02:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11521/">test-portal-acceptance-pullrequest(master)#11521</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11521/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1121">liferay-appsec#1121</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2306976278">[master] ci:test:relevant - JessieZhao0714 &gt; liferay-appsec - PR#1121 - 2023-05-16[19:49:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/25496/">publish-testray-report#25496</a><br/></div></div>

2023-05-17 02:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6750/">test-portal-source-format#6750</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6750/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1121">liferay-appsec#1121</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2306988878">[master] ci:test:sf - JessieZhao0714 &gt; liferay-appsec - PR#1121 - 2023-05-16[19:49:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/25497/">publish-testray-report#25497</a><br/></div></div>

2023-05-17 04:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 292 out of 303 jobs passed in 1 hour 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2f1bffccccf0a0748f98ea94ea72429934ea8d3">e2f1bffccccf0a0748f98ea94ea72429934ea8d3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2f1bffccccf0a0748f98ea94ea72429934ea8d3">e2f1bffccccf0a0748f98ea94ea72429934ea8d3</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2306184064">EE Development Acceptance (master) - 4540 - 2023-05-16[08:36:52]</a></p><details><summary><strong>ci:test:security - 292 out of 303 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11522/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/197283/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/538983/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573138/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628897/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/539572/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/525078/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/103154/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485022/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573139/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628898/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/492396/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/603617/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/128945/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380801/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/571847/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/525073/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/539569/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628900/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/521972/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506362/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380807/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/128951/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390842/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/538987/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/571853/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/603623/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/603618/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/521966/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/525074/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/571848/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380802/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/128946/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/492390/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628895/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506356/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/539570/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628899/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506361/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380806/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/128950/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/538986/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/539574/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573141/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/525079/">functional-tomcat90-mysql57-jdk8/1/17</a></li>< [...]

2023-05-17 04:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11522/">test-portal-acceptance-pullrequest(master)#11522</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11522/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1121">liferay-appsec#1121</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2307036066">[master] ci:test:security - JessieZhao0714 &gt; liferay-appsec - PR#1121 - 2023-05-16[19:49:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/25502/">publish-testray-report#25502</a><br/></div></div>

2023-05-17 08:09 UTC, gaborlovasdotcom requested changes
See my review comments.

2023-05-17 08:09 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +			if (IsElementPresent.pauseIsElementPresent(locator1 = "Button#I_AGREE")) {
Please define a new macro for these IF logics

2023-05-17 08:09 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SAML.testcase
> +			if (IsElementPresent(locator1 = "Select#QUESTION")) {
Can be combined with this IF also.

2023-05-18 01:36 UTC, JessieZhao0714 commented
ci:test:sf

2023-05-18 01:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/6780/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6780/jenkins-report.html">here</a>.</b></p>

2023-05-18 01:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b440f3015d9ce4472d4c7e36c503b0c6c724f5ba">b440f3015d9ce4472d4c7e36c503b0c6c724f5ba</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JessieZhao0714/liferay-portal/tree/master-qa-170942">master-qa-170942</a><br/>Branch GIT ID: <a href="https://github.com/JessieZhao0714/liferay-portal/commit/30109f7c86852256c4eca2aeee7774dafb51d34c">30109f7c86852256c4eca2aeee7774dafb51d34c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6780/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6780/jenkins-report.html">here</a>.</h5></details></html>

2023-05-18 01:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6780/">test-portal-source-format#6780</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6780/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1121">liferay-appsec#1121</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2308210607">[master] ci:test:sf - JessieZhao0714 &gt; liferay-appsec - PR#1121 - 2023-05-17[18:36:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/25571/">publish-testray-report#25571</a><br/></div></div>

2023-05-18 01:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/4796/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4796/jenkins-report.html">here</a>.</b></p>

2023-05-18 03:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 295 out of 303 jobs passed in 1 hour 14 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b440f3015d9ce4472d4c7e36c503b0c6c724f5ba">b440f3015d9ce4472d4c7e36c503b0c6c724f5ba</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bc3bbdcd4814f9bbb15cc5c79501c94fb52aaa08">bc3bbdcd4814f9bbb15cc5c79501c94fb52aaa08</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2308220811">EE Development Acceptance (master) - 4542 - 2023-05-17[16:35:08]</a></p><details><summary><strong>ci:test:security - 295 out of 303 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/4796/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/105080/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/541385/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494036/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630794/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/392637/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526533/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/574504/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/105075/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519780/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/540869/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630795/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/605640/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130946/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/523655/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/540866/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519777/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/486550/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519783/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130951/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/486555/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/382657/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130952/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/540872/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519784/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526536/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/486556/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130947/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/605641/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573598/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/523656/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/507577/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/574502/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/605642/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/392635/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/540867/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519778/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/573601/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526535/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/486554/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519782/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/540871/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/105078/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/507580/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494037/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li [...]

2023-05-18 03:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/4796/">test-portal-acceptance-pullrequest(master)#4796</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4796/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1121">liferay-appsec#1121</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2308259640">[master] ci:test:security - JessieZhao0714 &gt; liferay-appsec - PR#1121 - 2023-05-17[18:48:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/10415/">publish-testray-report#10415</a><br/></div></div>

2023-05-18 10:20 UTC, gaborlovasdotcom approved these changes
LGTM

2023-05-18 10:21 UTC, gaborlovasdotcom commented
ci:forward

2023-05-18 10:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-18 10:21 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-05-18 10:22 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-37.liferay.com/job/forward-pullrequest/1236//consoleFull)

2023-05-18 10:24 UTC, closed without merging

2023-05-18 10:24 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/135007
[Console](https://test-1-37.liferay.com/job/forward-pullrequest/1236//consoleFull)