LPS-184923 | master
liferay-appsec/liferay-portal pull request #1223
Opened 2023-07-13 04:20 UTC by JessieZhao0714

https://liferay.atlassian.net/browse/LPS-184923

2023-07-13 04:20 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**security**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-07-13 04:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/5803/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5803/jenkins-report.html">here</a>.</b></p>

2023-07-13 04:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/13121/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13121/jenkins-report.html">here</a>.</b></p>

2023-07-13 04:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69a21ffc7f14f5129b1b14e5de3cb78e4bef7fa2">69a21ffc7f14f5129b1b14e5de3cb78e4bef7fa2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JessieZhao0714/liferay-portal/tree/master-qa-184923">master-qa-184923</a><br/>Branch GIT ID: <a href="https://github.com/JessieZhao0714/liferay-portal/commit/f83a8e7e45f5e4420ca60e9e055178310850bc1f">f83a8e7e45f5e4420ca60e9e055178310850bc1f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5803/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5803/jenkins-report.html">here</a>.</h5></details></html>

2023-07-13 04:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1900/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1900/jenkins-report.html">here</a>.</b></p>

2023-07-13 04:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5803/">test-portal-source-format#5803</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5803/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1223">liferay-appsec#1223</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2381123852">[master] ci:test:sf - JessieZhao0714 &gt; liferay-appsec - PR#1223 - 2023-07-12[21:26:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/4076/">publish-testray-report#4076</a><br/></div></div>

2023-07-13 04:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/13121/">test-portal-acceptance-pullrequest(master)#13121</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13121/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1223">liferay-appsec#1223</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2381127327">[master] ci:test:relevant - JessieZhao0714 &gt; liferay-appsec - PR#1223 - 2023-07-12[21:30:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/28467/">publish-testray-report#28467</a><br/></div></div>

2023-07-13 06:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1900/">test-portal-acceptance-pullrequest(master)#1900</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1900/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1223">liferay-appsec#1223</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2381171410">[master] ci:test:security - JessieZhao0714 &gt; liferay-appsec - PR#1223 - 2023-07-12[21:33:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/3811/">publish-testray-report#3811</a><br/></div></div>

2023-07-14 01:59 UTC, JoyceWang08211 requested changes

2023-07-14 01:59 UTC, JoyceWang08211 commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/administration/auditing/Audit.testcase
> +				expected = "X-Liferay-Request-Company: 20096");
The companyId will change after a period of time, try not to write a fixed value, please use JSON to get values.

2023-07-14 01:59 UTC, JoyceWang08211 commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/administration/auditing/Audit.testcase
> +				expected = "X-Liferay-Request-Group: 20119");
The groupId will change after a period of time, try not to write a fixed value, please use JSON to get values.

2023-07-17 07:39 UTC, JessieZhao0714 commented
ci:test:security

2023-07-17 07:39 UTC, JessieZhao0714 commented
ci:test:sf

2023-07-17 07:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/4777/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4777/jenkins-report.html">here</a>.</b></p>

2023-07-17 07:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/71c21c513239d1c77aa1abd77d51cdffa7cff191">71c21c513239d1c77aa1abd77d51cdffa7cff191</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JessieZhao0714/liferay-portal/tree/master-qa-184923">master-qa-184923</a><br/>Branch GIT ID: <a href="https://github.com/JessieZhao0714/liferay-portal/commit/e6bfcaecd9b82f9b2217bf3400bddf92dfc1b65a">e6bfcaecd9b82f9b2217bf3400bddf92dfc1b65a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4777/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4777/jenkins-report.html">here</a>.</h5></details></html>

2023-07-17 07:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4777/">test-portal-source-format#4777</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4777/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1223">liferay-appsec#1223</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2384499911">[master] ci:test:sf - JessieZhao0714 &gt; liferay-appsec - PR#1223 - 2023-07-17[00:40:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/17251/">publish-testray-report#17251</a><br/></div></div>

2023-07-17 11:46 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 316 out of 328 jobs passed in 3 hours 15 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4690">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1407401_4233</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/71c21c513239d1c77aa1abd77d51cdffa7cff191">71c21c513239d1c77aa1abd77d51cdffa7cff191</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6cbdbb46c83b6baeb9d0a137b1e6bb3694ed2ece">6cbdbb46c83b6baeb9d0a137b1e6bb3694ed2ece</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2384518688">EE Development Acceptance (master) - 4689 - 2023-07-16[20:37:22]</a></p><details><summary><strong>ci:test:security - 316 out of 328 jobs PASSED</strong></summary><div><h4>12 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/4233/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/735823/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208090/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618187/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/603981/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665837/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233958/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/640708/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/484583/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/570327/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/735804/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708468/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/638566/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/640703/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/603974/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/578816/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208083/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/735795/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/566064/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/570338/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/578837/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708483/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/570340/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/570341/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233973/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708485/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618205/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/578818/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485044/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208085/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/735796/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208084/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/605088/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618184/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/570320/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/570319/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618182/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/578829/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/640714/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/735810/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/735811/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/603987/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test [...]

2023-07-17 11:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/4233/">test-portal-acceptance-pullrequest(master)#4233</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4233/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1223">liferay-appsec#1223</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2384557826">[master] ci:test:security - JessieZhao0714 &gt; liferay-appsec - PR#1223 - 2023-07-17[01:30:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/7813/">publish-testray-report#7813</a><br/></div></div>

2023-07-18 09:38 UTC, gaborlovasdotcom approved these changes

2023-07-18 09:39 UTC, gaborlovasdotcom commented
ci:forward

2023-07-18 09:39 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-07-18 09:39 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-07-18 09:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/1248//consoleFull)

2023-07-18 09:41 UTC, closed without merging