LRQA-82698 | master
liferay-appsec/liferay-portal pull request #1361
Opened 2023-09-06 01:11 UTC by JessieZhao0714

https://liferay.atlassian.net/browse/LRQA-82698

2023-09-06 01:12 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**security**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-09-06 01:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2734632486accdb4ef0ea2df712365c77e85932">e2734632486accdb4ef0ea2df712365c77e85932</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JessieZhao0714/liferay-portal/tree/master-qa-82698">master-qa-82698</a><br/>Branch GIT ID: <a href="https://github.com/JessieZhao0714/liferay-portal/commit/d8bdc5f8e053b0d2b15c8e5dd07473d56d98edca">d8bdc5f8e053b0d2b15c8e5dd07473d56d98edca</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1537/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1537/jenkins-report.html">here</a>.</h5></details></html>

2023-09-06 01:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1537/">test-portal-source-format#1537</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1537/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1361">liferay-appsec#1361</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419263919">[master] ci:test:sf - JessieZhao0714 &gt; liferay-appsec - PR#1361 - 2023-09-05[18:12:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/6115/">publish-testray-report#6115</a><br/></div></div>

2023-09-06 01:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/7163/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7163/jenkins-report.html">here</a>.</b></p>

2023-09-06 01:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3114/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3114/jenkins-report.html">here</a>.</b></p>

2023-09-06 03:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 321 out of 328 jobs passed in 2 hours 22 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2734632486accdb4ef0ea2df712365c77e85932">e2734632486accdb4ef0ea2df712365c77e85932</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2734632486accdb4ef0ea2df712365c77e85932">e2734632486accdb4ef0ea2df712365c77e85932</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419299566">EE Development Acceptance (master) - 1 - 2023-09-05[14:48:24]</a></p><details><summary><strong>ci:test:security - 321 out of 328 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/7163/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281794/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325778/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637828/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801287/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/566236/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325779/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/579096/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309938/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309939/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/726738/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637829/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/566234/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637826/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751056/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/656594/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/719287/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/656595/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751062/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/726741/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/719294/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/656602/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/566240/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/671949/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/704490/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801291/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637832/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/656597/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/827286/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/704486/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/827287/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/702071/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/679741/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309936/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/625399/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/656598/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/726736/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309940/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/579098/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/726740/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/719291/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751061/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/625402/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/827292/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801290/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li>< [...]

2023-09-06 03:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/7163/">test-portal-acceptance-pullrequest(master)#7163</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7163/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1361">liferay-appsec#1361</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419373366">[master] ci:test:security - JessieZhao0714 &gt; liferay-appsec - PR#1361 - 2023-09-05[18:25:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/14626/">publish-testray-report#14626</a><br/></div></div>

2023-09-06 07:43 UTC, gaborlovasdotcom requested changes

2023-09-06 07:43 UTC, gaborlovasdotcom commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/security/ldap/LDAP.testcase
> +		}
Hi @JessieZhao0714, I think we need an additional logout and re-login step just to confirm, these data was saved to LDAP server also, so when you log back in, the data remains the same

2023-09-06 08:45 UTC, JessieZhao0714 commented
ci:test:ldap

2023-09-06 08:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/5365/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5365/jenkins-report.html">here</a>.</b></p>

2023-09-06 08:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2734632486accdb4ef0ea2df712365c77e85932">e2734632486accdb4ef0ea2df712365c77e85932</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JessieZhao0714/liferay-portal/tree/master-qa-82698">master-qa-82698</a><br/>Branch GIT ID: <a href="https://github.com/JessieZhao0714/liferay-portal/commit/7e2ad1f826546565f3d767eefeabb973f8549180">7e2ad1f826546565f3d767eefeabb973f8549180</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5365/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5365/jenkins-report.html">here</a>.</h5></details></html>

2023-09-06 08:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5365/">test-portal-source-format#5365</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5365/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1361">liferay-appsec#1361</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419489014">[master] ci:test:sf - JessieZhao0714 &gt; liferay-appsec - PR#1361 - 2023-09-06[01:45:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/4038/">publish-testray-report#4038</a><br/></div></div>

2023-09-06 11:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:ldap - 26 out of 28 jobs passed in 2 hours 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2734632486accdb4ef0ea2df712365c77e85932">e2734632486accdb4ef0ea2df712365c77e85932</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2734632486accdb4ef0ea2df712365c77e85932">e2734632486accdb4ef0ea2df712365c77e85932</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419299566">EE Development Acceptance (master) - 1 - 2023-09-05[14:48:24]</a></p><details><summary><strong>ci:test:ldap - 26 out of 28 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8872/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751447/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/638165/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/719689/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/261212/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/262323/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/638167/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/289768/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228133/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/310381/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228134/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/702376/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228131/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/289762/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/638164/">functional-tomcat90-mysql57-jdk8/0/12</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/252684/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/579546/">modules-integration-mysql57-jdk8/0/0</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/261208/"><strike>modules-semantic-versioning-jdk8/0/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751446/">modules-semantic-versioning-jdk8/0/1</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266997/">modules-semantic-versioning-jdk8/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/579543/">modules-semantic-versioning-jdk8/0/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/702374/">modules-semantic-versioning-jdk8/0/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/289765/">modules-semantic-versioning-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/579541/">modules-semantic-versioning-jdk8/0/6</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/263310/">modules-semantic-versioning-jdk8/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/638163/">modules-semantic-versioning-jdk8/0/8</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/261210/">modules-unit-jdk8/0/0</a></li></ul></li><li>semantic-versioning-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/656936/">semantic-versioning-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8872/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at e2734632486accdb4ef0ea2df712365c77e85932:</strong></summary><ol><li><div><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/261208//consoleText">modules-semantic-versioning-jdk8/0/0</a><ol><li><details><summary><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/261208/testReport/com.liferay.semantic.versioning/SemanticVersioningTest">com.liferay.semantic.versioning.SemanticVersioningTest</a></summary><div><ol><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/261208//testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_analytics_analytics_message_sender_api_">testSemanticVersioning[/apps/analytics/analytics-message-sender-api]</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2023-09-06 11:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8872/">test-portal-acceptance-pullrequest(master)#8872</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8872/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>ldap<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/1361">liferay-appsec#1361</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419556813">[master] ci:test:ldap - JessieZhao0714 &gt; liferay-appsec - PR#1361 - 2023-09-06[02:21:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/18225/">publish-testray-report#18225</a><br/></div></div>

2023-09-07 10:01 UTC, gaborlovasdotcom approved these changes

2023-09-07 10:01 UTC, gaborlovasdotcom commented
ci:forward

2023-09-07 10:01 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-09-07 10:01 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-09-07 10:03 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-17.liferay.com/job/forward-pullrequest/411//consoleFull)

2023-09-07 10:04 UTC, closed without merging

2023-09-07 10:04 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/140399
[Console](https://test-1-17.liferay.com/job/forward-pullrequest/411//consoleFull)