Lps 122202 delete specific authenticor
liferay-appsec/liferay-portal pull request #162
Opened 2020-10-30 12:06 UTC by arthurchan35

2020-10-30 12:06 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-10-30 12:07 UTC, arthurchan35 commented
Add support to allow user to delete a specific authenticator.
Delete setup_complete.jsp, and move deleting all authenticators to setup.jsp

2020-10-30 12:07 UTC, arthurchan35 commented
ci:test:relevant

2020-10-30 12:08 UTC, arthurchan35 commented
ci:test:sf

2020-10-30 12:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/4623/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-portal-source-format/builds/4623/jenkins-report.html">here</a>.</b></p>

2020-10-30 12:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/02396f764ad152bde79f062c7cb1ca941a670234">02396f764ad152bde79f062c7cb1ca941a670234</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPS-122202-delete-specific-authenticor">LPS-122202-delete-specific-authenticor</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/244a2f870fc2b9aaf049548032ede18ea922a1df">244a2f870fc2b9aaf049548032ede18ea922a1df</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/4623/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/4623/jenkins-report.html">here</a>.</h5></details></html>

2020-10-30 12:15 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-18.liferay.com/job/test-portal-source-format/4623/">test-portal-source-format#4623</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/4623/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-appsec/liferay-portal/pull/162">liferay-appsec#162</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/55928.aspx">master - liferay-appsec > liferay-appsec - PR#162 - 2020-10-30[05:08:29]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/7298/">publish-spira-report#7298</a><br />

2020-10-30 12:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/3787/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3787/jenkins-report.html">here</a>.</b></p>

2020-11-03 15:41 UTC, csierra commented on modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/java/com/liferay/multi/factor/authentication/fido2/web/internal/checker/FIDO2BrowserSetupMFAChecker.java
> +
it looks like we are not checking anywere if the user is entitled to remove the credentialEntryId, what if a user tampers with the form and forges a credentialEntryId, is that a feasible scenario?
we should put a check in place to match current user with the credentialEntryId or add a permission check?

2020-11-03 15:53 UTC, csierra approved these changes
hey @arthurchan35, please see my comments attached and a change I have pushed. 
please double check if the order of the params in the form is the one we are used to send.

Thx in advance.

2020-11-03 15:53 UTC, csierra commented on modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/java/com/liferay/multi/factor/authentication/fido2/web/internal/portlet/action/MFAFIDO2UserAccountSetupMVCActionCommand.java
> +				new PropertyServiceReferenceMapper<>("service.id"));
Do we need to implement this logic inside `SetupMFAChecker`?
I understand `SetupMFAChecker` is the interface to the MFA framework but this logic is additional or _outside_ the framework, so it looks we could move `removeCredentialEntry` to this class and spare having to get the actual `SetupMFAChecker`.

2020-11-03 15:53 UTC, csierra commented on modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/java/com/liferay/multi/factor/authentication/fido2/web/internal/portlet/action/MFAFIDO2UserAccountSetupMVCActionCommand.java
> +	}
this is probable not needed either

2020-11-03 15:53 UTC, csierra commented on modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/java/com/liferay/multi/factor/authentication/fido2/web/internal/portlet/action/MFAFIDO2UserAccountSetupMVCActionCommand.java
> +		}
this can probably be spared too...

2020-11-03 15:53 UTC, csierra commented on modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/java/com/liferay/multi/factor/authentication/fido2/web/internal/portlet/action/MFAFIDO2UserAccountSetupMVCActionCommand.java
> +			actionRequest, "authenticatorId");
it looks like we need to pair this with the user or at least the company, we can't trust the data from the request.

2020-11-03 15:53 UTC, csierra commented on modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/java/com/liferay/multi/factor/authentication/fido2/web/internal/portlet/action/MFAFIDO2UserAccountSetupMVCActionCommand.java
> +			fido2BrowserSetupMFAChecker.removeCredentialEntry(authenticatorId);
it looks we can implement this method in this very class

2020-11-03 15:53 UTC, csierra commented on modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/java/com/liferay/multi/factor/authentication/fido2/web/internal/portlet/action/MFAFIDO2UserAccountSetupMVCActionCommand.java
> +		_mfaCheckerServiceTrackerMap;
not needed

2020-11-03 15:53 UTC, csierra commented on modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/java/com/liferay/multi/factor/authentication/fido2/web/internal/checker/FIDO2BrowserSetupMFAChecker.java
> +	public void removeCredentialEntry(long credentialEntryId) {
we can move this implementation to the action directly since this does not need to be implemented on the checker

2020-11-03 15:57 UTC, csierra requested changes
hey @arthurchan35, please see my comments attached and a change I have pushed. 
please double check if the order of the params in the form is the one we are used to send.

Thx in advance.

2020-11-05 14:45 UTC, arthurchan35 commented
https://github.com/liferay-appsec/liferay-portal/pull/163

2020-11-05 14:45 UTC, closed without merging