LPD-35470
liferay-appsec/liferay-portal pull request #2081
Opened 2024-11-25 18:43 UTC by manuelecastro

2024-11-25 18:43 UTC, liferay-continuous-integration commented
The following guidelines have been set by the owner of this repository: 
- &nbsp;&nbsp;&nbsp;&nbsp;"Thank you for sending this PR to liferay-appsec! Here is the [guide](https://liferay.atlassian.net/wiki/spaces/ENGAPPSECURITY/pages/1510735976/How+to+send+Pull+Request+to+the+Application+Security+Team+liferay-appsec) about 'How to send Pull Requests to the Application Security Team liferay-appsec'. For additional help,reach out in the #help-app-security Slack channel."

2024-11-25 18:43 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-11-25 18:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6811/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6811/jenkins-report.html">here</a>.</b></p>

2024-11-25 18:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bd8371069d06f7c3738f40f1d92732529e6a4692">bd8371069d06f7c3738f40f1d92732529e6a4692</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-35470-i-1">LPD-35470-i-1</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/80f246f3bf7dca1787cde9f29cb0f36e1698f80f">80f246f3bf7dca1787cde9f29cb0f36e1698f80f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6811/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6811/jenkins-report.html">here</a>.</h5></details></html>

2024-11-25 19:32 UTC, manuelecastro commented
ci:test:sf

2024-11-25 19:32 UTC, manuelecastro commented
ci:test:scim

2024-11-25 19:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>scim</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11495/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11495/jenkins-report.html">here</a>.</b></p>

2024-11-25 19:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6812/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6812/jenkins-report.html">here</a>.</b></p>

2024-11-25 19:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bd8371069d06f7c3738f40f1d92732529e6a4692">bd8371069d06f7c3738f40f1d92732529e6a4692</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-35470-i-1">LPD-35470-i-1</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/0ba14ecc71f771e834732cad23954ee8e69d8521">0ba14ecc71f771e834732cad23954ee8e69d8521</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6812/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6812/jenkins-report.html">here</a>.</h5></details></html>

2024-11-25 19:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6812/">test-portal-source-format#6812</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6812/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2081">liferay-appsec#2081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/76844849">[master] ci:test:sf - liferay-appsec &gt; liferay-appsec - PR#2081 - 2024-11-25[11:32:40]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>76844849<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/25990/">publish-testray-report#25990</a><br/></div></div>

2024-11-25 22:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:scim - 13 out of 16 jobs passed in 2 hours 9 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1041">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1387401_11495</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bd8371069d06f7c3738f40f1d92732529e6a4692">bd8371069d06f7c3738f40f1d92732529e6a4692</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/87c6985160fac31ac94e95ea4b9fc4f2add2775f">87c6985160fac31ac94e95ea4b9fc4f2add2775f</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/76851059">EE Development Acceptance (master) - 1040 - 2024-11-25[08:36:33]</a></p><details><summary><strong>ci:test:scim - 13 out of 16 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11495/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1263040/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/964632/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143535/">functional-tomcat90-mysql57/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131613/">js-unit/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240044/"><strike>js-unit/1/0</strike></a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792214/">modules-integration-mysql57/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240042/">modules-semantic-versioning/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240043/"><strike>modules-semantic-versioning/0/1</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094442/">modules-semantic-versioning/0/2</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131612/">modules-semantic-versioning/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029227/">modules-semantic-versioning/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/985439/">modules-semantic-versioning/0/5</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/964631/">modules-unit/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1263041/">playwright-js-tomcat90-mysql57/0/0</a></li></ul></li><li>semantic-versioning<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029228/">semantic-versioning/0/0</a></li></ul></li></ul></div><details><summary><strong>13 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11495/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240044//consoleText">js-unit/1/0</a><pre>Build was aborted</pre><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240044//testReport/commerce.commerce-frontend-js.test.components/GlobalSearch/Global_Search_When_responses_are_ok_When_input_is_filled_after_the_results_are_loaded_must_format_the_URL_templates_replacing_the_placeholders_with_entity_properties">commerce.commerce-frontend-js.test.components.GlobalSearch.Global Search When responses are ok When input is filled after the results are loaded must format the URL templates replacing the placeholders with entity properties</a><pre>Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
    at mapper (/opt/dev/projects/github/liferay-portal/modules/node_modules/jest-jasmine2/build/queueRunner.js:25:45)
    at /opt/dev/projects/github/liferay-portal/modules/node_modules/jest-jasmine2/build/queueRunner.js:73:41
    at processTicksAndRejections (node:internal/process/task_queues:95:5)</pre></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240044//testReport/commerce.commerce-frontend-js.test.components/GlobalSearch/Global_Search_When_responses_are_ok_When_input_is_filled_after_the_results_are_loaded_must_show_a_orders_list">commerce.commerce-frontend-js.test.components.GlobalSearch.Global Search When responses are ok When input is filled after the results are loaded must show a orders list</a><pre>Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
    at mapper (/opt/dev/projects/github/liferay-portal/modules/node_modules/jest-jasmine2/build/queueRunner.js:25:45)
    at /opt/dev/projects/github/liferay-portal/modules/node_modules/jest-jasmine2/build/queueRunner.js:73:41</pre></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240044//testReport/commerce.commerce-frontend-js.test.components/GlobalSearch/Global_Search_When_responses_are_ok_When_input_is_filled_after_the_results_are_loaded_must_show_an_account_list">commerce.commerce-frontend-js.test.components.GlobalSearch.Global Search When responses are ok When input is filled after the results are loaded must show an account list</a><pre>Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
    at mapper (/opt/dev/projects/github/liferay-portal/modules/node_modules/jest-jasmine2/build/queueRunner.js:25:45)
    at /opt/dev/projects/github/liferay-portal/modules/node_modules/jest-jasmine2/build/queueRunner.js:73:41</pre></div></li></ol></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240043//consoleText">modules-semantic-versioning/0/1</a><ol><li><details><summary><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240043/testReport/com.liferay.semantic.versioning/SemanticVersioningTest">com.liferay.semantic.versioning.SemanticVersioningTest</a></summary><div><ol><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downst [...]

2024-11-25 22:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11495/">test-portal-acceptance-pullrequest(master)#11495</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11495/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>scim<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2081">liferay-appsec#2081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/77011102">[master] ci:test:scim - liferay-appsec &gt; liferay-appsec - PR#2081 - 2024-11-25[11:32:48]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>77011102<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/23755/">publish-testray-report#23755</a><br/></div></div>

2024-11-25 22:07 UTC, stian-sigvartsen commented
ci:test:relevant

2024-11-25 22:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11929/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11929/jenkins-report.html">here</a>.</b></p>

2024-11-25 22:22 UTC, stian-sigvartsen requested changes
Hi @manuelecastro . This is a beautifully presented PR! 
Please consider my comment about the optimization.

2024-11-25 22:22 UTC, stian-sigvartsen commented on modules/dxp/apps/scim/scim-rest-test/src/testIntegration/java/com/liferay/scim/rest/resource/v1_0/test/UserResourceTest.java
> +		User user3 = testDeleteV2User_addUser();
I think we avoid creating a 3rd user here if you assert the successful update prior to changing the `scimClientId` of user2?

2024-11-25 23:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 29 out of 29 jobs passed in 1 hour 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bd8371069d06f7c3738f40f1d92732529e6a4692">bd8371069d06f7c3738f40f1d92732529e6a4692</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/87c6985160fac31ac94e95ea4b9fc4f2add2775f">87c6985160fac31ac94e95ea4b9fc4f2add2775f</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/76851059">EE Development Acceptance (master) - 1040 - 2024-11-25[08:36:33]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul><li>central-requirements<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1070027/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094635/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240199/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029839/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/491214/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094610/">js-unit/0/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385748/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029840/">modules-compile/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/980442/">modules-compile/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131803/">modules-compile/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1263190/">modules-compile/0/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143687/">modules-compile/0/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094638/">modules-compile/0/5</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/446220/">modules-compile/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143688/">modules-compile/0/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094639/">modules-compile/0/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/980441/">modules-compile/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1070050/">modules-compile/0/10</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/395098/">modules-compile/0/11</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1070051/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1047311/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094636/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094637/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240198/">unit_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 29 out of 29 jobs PASSED</strong></summary><details><summary><strong>29 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11929/">test-portal-acceptance-pullrequest(master)</a></li><li>central-requirements<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1070027/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094635/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1240199/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029839/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/491214/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094610/">js-unit/0/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385748/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029840/">modules-compile/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/980442/">modules-compile/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131803/">modules-compile/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1263190/">modules-compile/0/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143687/">modules-compile/0/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094638/">modules-compile/0/5</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/446220/">modules-compile/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1143688/">modules-compile/0/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1094639/">modules-compile/0/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/980441/">modules-compile/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1070050/">modules-compile/0/10</a> [...]

2024-11-25 23:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11929/">test-portal-acceptance-pullrequest(master)#11929</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11929/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2081">liferay-appsec#2081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/77083923">[master] ci:test:relevant - liferay-appsec &gt; liferay-appsec - PR#2081 - 2024-11-25[14:07:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>77083923<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/25994/">publish-testray-report#25994</a><br/></div></div>

2024-11-29 22:24 UTC, manuelecastro commented
Hey @stian-sigvartsen ! I've Just pushed some changes doing what you suggested. :)

2024-12-02 13:58 UTC, manuelecastro commented
ci:test:scim

2024-12-02 13:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>scim</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/6304/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6304/jenkins-report.html">here</a>.</b></p>

2024-12-02 14:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:scim - 13 out of 15 jobs passed in 58 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3c6658688fbb7f2435b3e20cff4a2d71b7c9d154">3c6658688fbb7f2435b3e20cff4a2d71b7c9d154</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/aa943208fe01a0f0630284b8f7fb301162cd300d">aa943208fe01a0f0630284b8f7fb301162cd300d</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/81178721">EE Development Acceptance (master) - 1054 - 2024-11-29[16:36:01]</a></p><details><summary><strong>ci:test:scim - 13 out of 15 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/6304/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/396222/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/396224/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/396225/">functional-tomcat90-mysql57/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/967800/">js-unit/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032522/">js-unit/1/0</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1135350/">modules-integration-mysql57/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1097770/">modules-semantic-versioning/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1135324/"><strike>modules-semantic-versioning/0/1</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1135323/">modules-semantic-versioning/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049707/">modules-semantic-versioning/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032745/">modules-semantic-versioning/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725626/">modules-semantic-versioning/0/5</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/396223/">playwright-js-tomcat90-mysql57/0/0</a></li></ul></li><li>semantic-versioning<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/796124/">semantic-versioning/0/0</a></li></ul></li></ul></div><details><summary><strong>13 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6304/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at aa943208fe01a0f0630284b8f7fb301162cd300d:</strong></summary><ol><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1135324//consoleText">modules-semantic-versioning/0/1</a><ol><li><details><summary><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1135324/testReport/com.liferay.semantic.versioning/SemanticVersioningTest">com.liferay.semantic.versioning.SemanticVersioningTest</a></summary><div><ol><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1135324//testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_frontend_data_set_frontend_data_set_api_">testSemanticVersioning[/apps/frontend-data-set/frontend-data-set-api]</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-12-02 15:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/6304/">test-portal-acceptance-pullrequest(master)#6304</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6304/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>scim<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2081">liferay-appsec#2081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/81589085">[master] ci:test:scim - liferay-appsec &gt; liferay-appsec - PR#2081 - 2024-12-02[05:58:39]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>81589085<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/13013/">publish-testray-report#13013</a><br/></div></div>

2024-12-02 17:38 UTC, manuelecastro commented
All related tests have passed! :heavy_check_mark: 

![image](https://github.com/user-attachments/assets/745b2e28-920f-46cd-aad8-770334439b19)

2024-12-05 17:30 UTC, stian-sigvartsen approved these changes
Looks great @manuelecastro ! Thanks.

2024-12-05 17:30 UTC, stian-sigvartsen commented
ci:forward

2024-12-05 17:30 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-12-05 17:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/4271/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/4271/jenkins-report.html">here</a>.</b></p>

2024-12-05 17:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-35470-i-1">LPD-35470-i-1</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/59ba4f0dccc1e4da4e52c3c36ce3d64de4399d80">59ba4f0dccc1e4da4e52c3c36ce3d64de4399d80</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/4271/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/4271/jenkins-report.html">here</a>.</h5></details></html>

2024-12-05 17:40 UTC, stian-sigvartsen commented
ci:forward

2024-12-05 17:40 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-12-05 17:40 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2024-12-05 17:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/4271/">test-portal-source-format#4271</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/4271/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2081">liferay-appsec#2081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/84580949">[master] ci:test:sf - liferay-appsec &gt; liferay-appsec - PR#2081 - 2024-12-05[09:31:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>84580949<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/28245/">publish-testray-report#28245</a><br/></div></div>

2024-12-05 18:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10773/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10773/jenkins-report.html">here</a>.</b></p>

2024-12-05 19:28 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 23 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 27 out of 29 jobs passed in 1 hour 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/83965458">EE Development Acceptance (master) - 1060 - 2024-12-04[13:49:02]</a></p><details><summary><strong>ci:test:stable - 23 out of 24 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/990815/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269335/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269339/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969728/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969727/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269319/">js-unit/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269320/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040388/">modules-compile/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1244635/">modules-compile/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148679/">modules-compile/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1074739/">modules-compile/0/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148677/">modules-compile/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269337/">modules-compile/0/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969726/"><strike>modules-compile/0/6</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984291/">modules-compile/0/7</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1074740/">modules-compile/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269338/">modules-compile/0/9</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969725/">modules-compile/0/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034275/">modules-compile/0/11</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984292/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1244634/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269336/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034273/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148678/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 27 out of 29 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12124/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/990815/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269335/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269339/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969728/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969727/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269319/">js-unit/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269320/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040388/">modules-compile/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1244635/">modules-compile/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148679/">modules-compile/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1074739/">modules-compile/0/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148677/">modules-compile/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269337/">modules-compile/0/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969726/"><strike>modules-compile/0/6</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984291/">modules-compile/0/7</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1074740/">modules-compile/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269338/">modules-compile/0/9</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969725 [...]

2024-12-05 19:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12124/">test-portal-acceptance-pullrequest(master)#12124</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12124/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2081">liferay-appsec#2081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/84645422">[master] ci:test:relevant - liferay-appsec &gt; liferay-appsec - PR#2081 - 2024-12-05[10:19:18]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>84645422<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26423/">publish-testray-report#26423</a><br/></div></div>

2024-12-05 19:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 23 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 27 out of 29 jobs passed in 1 hour 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/83965458">EE Development Acceptance (master) - 1060 - 2024-12-04[13:49:02]</a></p><details><summary><strong>ci:test:stable - 23 out of 24 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384274/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040373/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798358/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040378/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448189/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384275/">js-unit/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448186/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/990822/">modules-compile/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984283/">modules-compile/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040379/">modules-compile/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798357/">modules-compile/0/3</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448187/">modules-compile/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/990820/">modules-compile/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269323/"><strike>modules-compile/0/6</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798355/">modules-compile/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040377/">modules-compile/0/8</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448188/">modules-compile/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040374/">modules-compile/0/10</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984282/">modules-compile/0/11</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798356/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/990821/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798354/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/990819/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040375/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 27 out of 29 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10773/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384274/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040373/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798358/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040378/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448189/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384275/">js-unit/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448186/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/990822/">modules-compile/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984283/">modules-compile/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040379/">modules-compile/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798357/">modules-compile/0/3</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448187/">modules-compile/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/990820/">modules-compile/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1269323/"><strike>modules-compile/0/6</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/798355/">modules-compile/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040377/">modules-compile/0/8</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448188/">modules-compile/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040374/">modules-compile/ [...]

2024-12-05 19:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10773/">test-portal-acceptance-pullrequest(master)#10773</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10773/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2081">liferay-appsec#2081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/84645456">[master] ci:test:relevant - liferay-appsec &gt; liferay-appsec - PR#2081 - 2024-12-05[10:07:46]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>84645456<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/23891/">publish-testray-report#23891</a><br/></div></div>

2024-12-06 09:49 UTC, stian-sigvartsen commented
ci:forward:force

2024-12-06 09:49 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-12-06 09:49 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`

2024-12-06 12:28 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 12 out of 27 jobs passed in 1 hour 52 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0da9269ab65490c5a393eb7ec1a656165e7d7b26">0da9269ab65490c5a393eb7ec1a656165e7d7b26</a></p><details><summary><strong>ci:test:stable - 12 out of 27 jobs PASSED</strong></summary><div><h4>15 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13260/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448584/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970330/"><strike>functional-smoke-tomcat90-mysql57_stable/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/799116/"><strike>functional-upgrade-tomcat90-mysql57_stable/0/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1270091/"><strike>functional-upgrade-tomcat90-mysql57_stable/0/1</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1138097/"><strike>functional-upgrade-tomcat90-mysql57_stable/0/2</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970340/"><strike>functional-upgrade-tomcat90-mysql57_stable/0/3</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/799115/"><strike>functional-upgrade-tomcat90-mysql57_stable/0/4</strike></a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/397503/">js-unit/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1149338/"><strike>js-unit/1/0</strike></a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970342/"><strike>modules-compile/0/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1138098/">modules-compile/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1035075/">modules-compile/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970341/"><strike>modules-compile/0/3</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970337/">modules-compile/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970336/"><strike>modules-compile/0/5</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970335/">modules-compile/0/6</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970333/"><strike>modules-compile/0/7</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1138096/">modules-compile/0/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1138095/">modules-compile/0/9</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970334/">modules-compile/0/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1270090/">modules-compile/0/11</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970339/"><strike>modules-compile/0/12</strike></a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1041066/"><strike>modules-integration-mysql57_stable/0/0</strike></a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970331/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970332/"><strike>playwright-js-tomcat90-mysql57_stable/0/0</strike></a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970338/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13260/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970330//consoleText">functional-smoke-tomcat90-mysql57_stable/0/0</a><pre>stop-docker-containers:
     [exec] Stopping container [ID: 'c8cc845c1796', name: 'test-1-33-88.lax.liferay.com_mysql']'
     [exec] test-1-33-88.lax.liferay.com_mysql
     [exec] test-1-33-88.lax.liferay.com_mysql
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/docker_stop.sh
     [exec] Stopping container [ID: '3eec41182961', name: 'test-1-33-88.lax.liferay.com_chrome']'
     [exec] test-1-33-88.lax.liferay.com_chrome
     [exec] test-1-33-88.lax.liferay.com_chrome
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/docker_stop.sh
[stopwatch] [run.batch.test.action: 7:52.294 sec]
     [echo] 
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1503807648.properties</pre><ol><li><div><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970330//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmoke_Smoke_">LocalFile.PortalSmoke#Smoke</a> - <a href="https://storage.cloud.google.com/testray-results/2024-12/test-1-27/test-portal-acceptance-pullrequest(master)/13260/functional-smoke-tomcat90-mysql57_stable/0/0/jenkins-console.txt.gz">Console Output</a> - <a>Failed 2 of last 23</a> - <a href="https://storage.cloud.google.com/testray-results/2024-12/test-1-27/test-portal-acceptance-pullrequest(master)/13260/functional-smoke-tomcat90-mysql57_stable/0/0/LocalFile.PortalSmoke_Smoke/liferay-log.txt.gz">Liferay Log</a></div></li></ol></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/799116//consoleText">functional-upgrade-tomcat90-mysql57_stable/0/0</a><pre>stop-docker-containers:
     [exec] Stopping container [ID: '56ca968dbce9', name: 'test-1-40-45.lax.liferay.com_mysql']'
     [exec] test-1-40-45.lax.liferay.com_mysql
     [exec] test-1-40-45.lax.liferay.com_mysql
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/docker_stop.sh
     [exec] Stopping container [ID: '5a55bfffc7f6', name: 'test-1-40-45.lax.liferay.com_chrome']'
     [exec] test-1-40-45.lax.liferay.com_chrome
     [exec] test-1-40-45.lax.liferay.com_chrome
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/docker_stop.sh
[stopwatch] [run.batch.test.action: 6:17.383 sec]
     [echo] 
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1900230093.properties</pre><ol><li><div><a href="htt [...]

2024-12-06 12:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13260/">test-portal-acceptance-pullrequest(master)#13260</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13260/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>stable<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2081">liferay-appsec#2081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/85351161">[master] ci:test:stable - liferay-appsec &gt; liferay-appsec - PR#2081 - 2024-12-06[02:00:34]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>85351161<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28960/">publish-testray-report#28960</a><br/></div></div>

2024-12-06 13:16 UTC, stian-sigvartsen commented
ci:test:relevant

2024-12-06 14:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10786/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10786/jenkins-report.html">here</a>.</b></p>

2024-12-06 15:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 29 out of 29 jobs passed in 1 hour 10 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fbd14f9070486cb67f22b032f18d381c06f23418">fbd14f9070486cb67f22b032f18d381c06f23418</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1d812550bf00975c9ad5830b8acb959e9ea70714">1d812550bf00975c9ad5830b8acb959e9ea70714</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/85068778">EE Development Acceptance (master) - 1062 - 2024-12-05[16:36:26]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul><li>central-requirements<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1075416/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1149565/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052021/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1149566/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494406/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1075417/">js-unit/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034890/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384706/">modules-compile/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984968/">modules-compile/0/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494407/">modules-compile/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1100349/">modules-compile/0/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/991635/">modules-compile/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/799347/">modules-compile/0/5</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453166/">modules-compile/0/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1152525/">modules-compile/0/7</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/468323/">modules-compile/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1100348/">modules-compile/0/9</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/443947/">modules-compile/0/10</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388236/">modules-compile/0/11</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1245353/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034913/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/397572/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1245352/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448659/">unit_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 29 out of 29 jobs PASSED</strong></summary><details><summary><strong>29 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10786/">test-portal-acceptance-pullrequest(master)</a></li><li>central-requirements<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1075416/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1149565/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052021/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1149566/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494406/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1075417/">js-unit/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034890/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384706/">modules-compile/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/984968/">modules-compile/0/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494407/">modules-compile/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1100349/">modules-compile/0/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/991635/">modules-compile/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/799347/">modules-compile/0/5</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453166/">modules-compile/0/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1152525/">modules-compile/0/7</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/468323/">modules-compile/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1100348/">modules-compile/0/9</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/443947/">modules-compile/0/10</a></li><li><a href=" [...]

2024-12-06 15:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10786/">test-portal-acceptance-pullrequest(master)#10786</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10786/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2081">liferay-appsec#2081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/85574015">[master] ci:test:relevant - liferay-appsec &gt; liferay-appsec - PR#2081 - 2024-12-06[06:06:21]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>85574015<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/23911/">publish-testray-report#23911</a><br/></div></div>

2024-12-06 16:35 UTC, stian-sigvartsen commented
ci:forward

2024-12-06 16:36 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-12-06 16:36 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1638//consoleFull)

2024-12-06 16:37 UTC, closed without merging

2024-12-06 16:37 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/156739
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1638//consoleFull)