LPD-41375 Replace java8 supported jodd.Paramo dependency with java21 compatible solution
liferay-appsec/liferay-portal pull request #2089
Opened 2024-11-27 14:15 UTC by jgarcialr

see https://liferay.atlassian.net/browse/LPD-41375
//cc @tomibiro

2024-11-27 14:15 UTC, liferay-continuous-integration commented
The following guidelines have been set by the owner of this repository: 
- &nbsp;&nbsp;&nbsp;&nbsp;"Thank you for sending this PR to liferay-appsec! Here is the [guide](https://liferay.atlassian.net/wiki/spaces/ENGAPPSECURITY/pages/1510735976/How+to+send+Pull+Request+to+the+Application+Security+Team+liferay-appsec) about 'How to send Pull Requests to the Application Security Team liferay-appsec'. For additional help,reach out in the #help-app-security Slack channel."

2024-11-27 14:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-11-27 14:16 UTC, jgarcialr commented
ci:test:relevant

2024-11-27 14:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7549/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7549/jenkins-report.html">here</a>.</b></p>

2024-11-27 14:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/14c7ec2ad3b34d50609351b4ec2e1b196a152849">14c7ec2ad3b34d50609351b4ec2e1b196a152849</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-41375-i">LPD-41375-i</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/9b1e85a9fc84d1b51988d54e94221cf2910ab63f">9b1e85a9fc84d1b51988d54e94221cf2910ab63f</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7549/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7549/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 5 formatting issues:
     [java] 1: ',' is not followed by whitespace., see https://checkstyle.sourceforge.io/checks/whitespace/whitespaceafter.html: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterMethodVisitor.java 61 (Checkstyle:WhitespaceAfterCheck)
     [java] 2: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/ExtractedParameter.java expected:&lt;...opyrightText: (c) 20[24] Liferay, Inc. https...&gt; but was:&lt;...opyrightText: (c) 20[00] Liferay, Inc. https...&gt;
     [java] 3: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractor.java expected:&lt;...opyrightText: (c) 20[24] Liferay, Inc. https...&gt; but was:&lt;...opyrightText: (c) 20[00] Liferay, Inc. https...&gt;
     [java] 4: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterClassVisitor.java expected:&lt;...opyrightText: (c) 20[24] Liferay, Inc. https...&gt; but was:&lt;...opyrightText: (c) 20[00] Liferay, Inc. https...&gt;
     [java] 5: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterMethodVisitor.java expected:&lt;...opyrightText: (c) 20[24 Liferay, Inc. https://liferay.com
     [java]  * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
     [java]  */
     [java] 
     [java] package com.liferay.portal.remote.json.web.service.web.internal.util;
     [java] 
     [java] import com.liferay.petra.string.StringUtil;
     [java] 
     [java] import java.lang.reflect.Method;
     [java] import java.lang.reflect.Modifier;
     [java] 
     [java] import java.util.ArrayList;
     [java] import java.util.List;
     [java] 
     [java] import org.objectweb.asm.Label;
     [java] import org.objectweb.asm.MethodVisitor;
     [java] import org.objectweb.asm.Opcodes;
     [java] 
     [java] /**
     [java]  * @author Jorge Garcia Jimenez
     [java]  */
     [java] public class MethodParameterMethodVisitor extends MethodVisitor \{
     [java] 
     [java]   public List&lt;ExtractedParameter&gt; getExtractedParameterList() \{</pre></details></html>

2024-11-27 14:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7549/">test-portal-source-format#7549</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7549/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/78962520">[master] ci:test:sf - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-27[06:15:48]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>78962520<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28759/">publish-testray-report#28759</a><br/></div></div>

2024-11-27 14:21 UTC, jgarcialr commented
ci:test:sf

2024-11-27 14:23 UTC, jgarcialr commented
ci:test:security

2024-11-27 14:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7550/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7550/jenkins-report.html">here</a>.</b></p>

2024-11-27 14:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13156/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13156/jenkins-report.html">here</a>.</b></p>

2024-11-27 14:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/14c7ec2ad3b34d50609351b4ec2e1b196a152849">14c7ec2ad3b34d50609351b4ec2e1b196a152849</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-41375-i">LPD-41375-i</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/077e1002a649146a6e909a117acbbc3c52022d38">077e1002a649146a6e909a117acbbc3c52022d38</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7550/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7550/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterMethodVisitor.java expected:&lt;...ernal.util;
     [java] 
     [java] import [com.liferay.petra.string.StringUtil;
     [java] 
     [java] import java.lang.reflect.Method;
     [java] import java.lang.reflect.Modifier;
     [java] 
     [java] import java.util.ArrayList;
     [java] import java.util.List;
     [java] 
     [java] import org.objectweb.asm.Label;
     [java] import org.objectweb.asm.MethodVisitor;
     [java] import org.objectweb.asm.Opcodes;
     [java] 
     [java] /**
     [java]  * @author Jorge Garcia Jimenez
     [java]  */
     [java] public class MethodParameterMethodVisitor extends MethodVisitor \{
     [java] 
     [java]   public List&lt;ExtractedParameter&gt; getExtractedParameterList() \{
     [java]     return _extractedParameterList;
     [java]   \}
     [java] 
     [java]   @Override
     [java]   public void visitLocalVariable(
     [java]     String name, String descriptor, String signature, Label start,
     [java]     Label end, int index) \{
     [java] 
     [java]     if (!Modifier.isStatic(_method.getModifiers()) &amp;&amp; (index == 0)) \{
     [java]       return;
     [java]     \}
     [java] 
     [java]     int count = 0;
     [java] 
     [java]     for (Class&lt;?&gt; parameterType : _method.getParameterTypes()) \{
     [java]       if (parameterType.getName(
     [java]         ).equalsIgnoreCase(
     [java]           long.class.getName()
     [java]         ) ||
     [java]         parameterType.getName(
     [java]         ).equalsIgnoreCase(
     [java]           double.class.getName()
     [java]         )) \{
     [java] 
     [java]         count++;
     [java]       \}
     [java]     \}
     [java] 
     [java]     if (index &lt;
     [java]         (_method.getParameterCount() +
     [java]           (Modifier.isStatic(_method.getModifiers()) ? 0 : 1) +
     [java]             count)) \{
     [java] 
     [java]       if (signature != null) \{
     [java]         String parameterSignature = StringUtil.removeSubstring(
     [java]           signature, descriptor]);
     [java] 
     [java]         _extractedPa...&gt; but was:&lt;...ernal.util;
     [java] 
     [java] import [java.lang.reflect.Method;
     [java] import java.lang.reflect.Modifier;
     [java] 
     [java] import java.util.ArrayList;
     [java] import java.util.List;
     [java] </pre></details></html>

2024-11-27 14:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7550/">test-portal-source-format#7550</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7550/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/78963120">[master] ci:test:sf - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-27[06:21:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>78963120<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28761/">publish-testray-report#28761</a><br/></div></div>

2024-11-27 14:45 UTC, jgarcialr commented
ci:test:sf

2024-11-27 14:47 UTC, jgarcialr commented
ci:test:sf

2024-11-27 14:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3957/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3957/jenkins-report.html">here</a>.</b></p>

2024-11-27 14:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f3bb3de3dbd03fc0211539a9b993df5515a5bef2">f3bb3de3dbd03fc0211539a9b993df5515a5bef2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-41375-i">LPD-41375-i</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/078f1a9a9d7358d782f8dc0d61cd10521b375aad">078f1a9a9d7358d782f8dc0d61cd10521b375aad</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7551/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7551/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterMethodVisitor.java expected:&lt;....string.StringUtil;
     [java] [
     [java] import java.lang.reflect.Method;
     [java] import java.lang.reflect.Modifier;
     [java] 
     [java] import java.util.ArrayList;
     [java] import java.util.List;
     [java] 
     [java] import org.objectweb.asm.Label;
     [java] import org.objectweb.asm.MethodVisitor;
     [java] import org.objectweb.asm.Opcodes;
     [java] 
     [java] /**
     [java]  * @author Jorge Garcia Jimenez
     [java]  */
     [java] public class MethodParameterMethodVisitor extends MethodVisitor \{
     [java] 
     [java]   public List&lt;ExtractedParameter&gt; getExtractedParameterList() \{
     [java]     return _extractedParameterList;
     [java]   \}
     [java] 
     [java]   @Override
     [java]   public void visitLocalVariable(
     [java]     String name, String descriptor, String signature, Label start,
     [java]     Label end, int index) \{
     [java] 
     [java]     if (!Modifier.isStatic(_method.getModifiers()) &amp;&amp; (index == 0)) \{
     [java]       return;
     [java]     \}
     [java] 
     [java]     int count = 0;
     [java] 
     [java]     for (Class&lt;?&gt; parameterType : _method.getParameterTypes()) \{
     [java]       if (parameterType.getName(
     [java]         ).equalsIgnoreCase(
     [java]           long.class.getName()
     [java]         ) ||
     [java]         parameterType.getName(
     [java]         ).equalsIgnoreCase(
     [java]           double.class.getName()
     [java]         )) \{
     [java] 
     [java]         count++;
     [java]       \}
     [java]     \}
     [java] 
     [java]     if (index &lt;
     [java]         (_method.getParameterCount() +
     [java]           (Modifier.isStatic(_method.getModifiers()) ? 0 : 1) +
     [java]             count)) \{
     [java] 
     [java]       if (signature != null) \{
     [java]         String parameterSignature = StringUtil.removeSubstring(
     [java]           signature, descriptor]);
     [java] 
     [java]         _extractedPa...&gt; but was:&lt;....string.StringUtil;
     [java] [import com.liferay.petra.string.StringPool;
     [java] 
     [java] import java.lang.reflect.Method;
     [java] import java.lang.reflect.Modifier;
     [java] 
     [java] import java.util.ArrayList;
     [java] import java.util.List;
     [java] </pre></details></html>

2024-11-27 14:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f3bb3de3dbd03fc0211539a9b993df5515a5bef2">f3bb3de3dbd03fc0211539a9b993df5515a5bef2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-41375-i">LPD-41375-i</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/078f1a9a9d7358d782f8dc0d61cd10521b375aad">078f1a9a9d7358d782f8dc0d61cd10521b375aad</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3957/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3957/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterMethodVisitor.java expected:&lt;....string.StringUtil;
     [java] [
     [java] import java.lang.reflect.Method;
     [java] import java.lang.reflect.Modifier;
     [java] 
     [java] import java.util.ArrayList;
     [java] import java.util.List;
     [java] 
     [java] import org.objectweb.asm.Label;
     [java] import org.objectweb.asm.MethodVisitor;
     [java] import org.objectweb.asm.Opcodes;
     [java] 
     [java] /**
     [java]  * @author Jorge Garcia Jimenez
     [java]  */
     [java] public class MethodParameterMethodVisitor extends MethodVisitor \{
     [java] 
     [java]   public List&lt;ExtractedParameter&gt; getExtractedParameterList() \{
     [java]     return _extractedParameterList;
     [java]   \}
     [java] 
     [java]   @Override
     [java]   public void visitLocalVariable(
     [java]     String name, String descriptor, String signature, Label start,
     [java]     Label end, int index) \{
     [java] 
     [java]     if (!Modifier.isStatic(_method.getModifiers()) &amp;&amp; (index == 0)) \{
     [java]       return;
     [java]     \}
     [java] 
     [java]     int count = 0;
     [java] 
     [java]     for (Class&lt;?&gt; parameterType : _method.getParameterTypes()) \{
     [java]       if (parameterType.getName(
     [java]         ).equalsIgnoreCase(
     [java]           long.class.getName()
     [java]         ) ||
     [java]         parameterType.getName(
     [java]         ).equalsIgnoreCase(
     [java]           double.class.getName()
     [java]         )) \{
     [java] 
     [java]         count++;
     [java]       \}
     [java]     \}
     [java] 
     [java]     if (index &lt;
     [java]         (_method.getParameterCount() +
     [java]           (Modifier.isStatic(_method.getModifiers()) ? 0 : 1) +
     [java]             count)) \{
     [java] 
     [java]       if (signature != null) \{
     [java]         String parameterSignature = StringUtil.removeSubstring(
     [java]           signature, descriptor]);
     [java] 
     [java]         _extractedPa...&gt; but was:&lt;....string.StringUtil;
     [java] [import com.liferay.petra.string.StringPool;
     [java] 
     [java] import java.lang.reflect.Method;
     [java] import java.lang.reflect.Modifier;
     [java] 
     [java] import java.util.ArrayList;
     [java] import java.util.List;
     [java] </pre></details></html>

2024-11-27 14:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3957/">test-portal-source-format#3957</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3957/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/78973654">[master] ci:test:sf - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-27[06:46:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>78973654<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/15540/">publish-testray-report#15540</a><br/></div></div>

2024-11-27 15:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 28 out of 29 jobs passed in 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/14c7ec2ad3b34d50609351b4ec2e1b196a152849">14c7ec2ad3b34d50609351b4ec2e1b196a152849</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/255d7b8d9e411a51a994b1adc4d1d415d47518ec">255d7b8d9e411a51a994b1adc4d1d415d47518ec</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/78687707">EE Development Acceptance (master) - 1046 - 2024-11-26[20:44:21]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 27 out of 29 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11846/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133325/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133336/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241444/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030893/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264781/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096019/">js-unit/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048331/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987106/">modules-compile/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036568/">modules-compile/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966028/">modules-compile/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145032/">modules-compile/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030892/">modules-compile/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264780/">modules-compile/0/5</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145031/">modules-compile/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133337/">modules-compile/0/7</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724281/">modules-compile/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241443/">modules-compile/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241442/">modules-compile/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036567/">modules-compile/0/11</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987105/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241441/"><strike>modules-integration-mysql57/0/0</strike></a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793859/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036555/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133338/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793856/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133339/">playwright-js-tomcat90-mysql57/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793857/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793858/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11846/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 255d7b8d9e411a51a994b1adc4d1d415d47518ec:</strong></summary><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241441//consoleText">modules-integration-mysql57/0/0</a><ol><li><details><summary><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241441/testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest">com.liferay.portal.remote.cors.client.test.AnnotationCORSClientTest</a> - <a>Failed 21 of last 21</a></summary><div><ol><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241441//testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest/testApplicationAnnotationCORSForGuestUser">testApplicationAnnotationCORSForGuestUser</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241441//testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest/testApplicationAnnotationCORSWithoutOAuth2">testApplicationAnnotationCORSWithoutOAuth2</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-11-27 15:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11846/">test-portal-acceptance-pullrequest(master)#11846</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11846/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/79013075">[master] ci:test:relevant - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-27[06:16:44]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79013075<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/25947/">publish-testray-report#25947</a><br/></div></div>

2024-11-27 15:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 28 out of 29 jobs passed in 59 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/14c7ec2ad3b34d50609351b4ec2e1b196a152849">14c7ec2ad3b34d50609351b4ec2e1b196a152849</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/255d7b8d9e411a51a994b1adc4d1d415d47518ec">255d7b8d9e411a51a994b1adc4d1d415d47518ec</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/78687707">EE Development Acceptance (master) - 1046 - 2024-11-26[20:44:21]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 27 out of 29 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13156/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264767/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793871/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071292/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133353/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793874/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030884/">js-unit/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048336/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148708/">modules-compile/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036582/">modules-compile/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036584/">modules-compile/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145041/">modules-compile/0/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981579/">modules-compile/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793873/">modules-compile/0/5</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793872/">modules-compile/0/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036583/">modules-compile/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264789/">modules-compile/0/8</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030902/">modules-compile/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264788/">modules-compile/0/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030903/">modules-compile/0/11</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048351/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096042/"><strike>modules-integration-mysql57/0/0</strike></a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096041/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966021/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096043/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981578/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966041/">playwright-js-tomcat90-mysql57/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048350/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133352/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13156/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 255d7b8d9e411a51a994b1adc4d1d415d47518ec:</strong></summary><ol><li><div><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096042//consoleText">modules-integration-mysql57/0/0</a><ol><li><details><summary><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096042/testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest">com.liferay.portal.remote.cors.client.test.AnnotationCORSClientTest</a> - <a>Failed 21 of last 21</a></summary><div><ol><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096042//testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest/testApplicationAnnotationCORSForGuestUser">testApplicationAnnotationCORSForGuestUser</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096042//testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest/testApplicationAnnotationCORSWithoutOAuth2">testApplicationAnnotationCORSWithoutOAuth2</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-11-27 15:40 UTC, jgarcialr commented
ci:test:sf

2024-11-27 15:40 UTC, jgarcialr commented
ci:test:relevant

2024-11-27 15:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11847/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11847/jenkins-report.html">here</a>.</b></p>

2024-11-27 15:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6837/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6837/jenkins-report.html">here</a>.</b></p>

2024-11-27 15:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f3bb3de3dbd03fc0211539a9b993df5515a5bef2">f3bb3de3dbd03fc0211539a9b993df5515a5bef2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-41375-i">LPD-41375-i</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/a538081786812664a7482dcfdebcc5348e65d010">a538081786812664a7482dcfdebcc5348e65d010</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6837/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6837/jenkins-report.html">here</a>.</h5></details></html>

2024-11-27 15:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6837/">test-portal-source-format#6837</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6837/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/79078693">[master] ci:test:sf - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-27[07:40:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79078693<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26074/">publish-testray-report#26074</a><br/></div></div>

2024-11-27 15:56 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 351 out of 358 jobs passed in 1 hour 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/14c7ec2ad3b34d50609351b4ec2e1b196a152849">14c7ec2ad3b34d50609351b4ec2e1b196a152849</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/255d7b8d9e411a51a994b1adc4d1d415d47518ec">255d7b8d9e411a51a994b1adc4d1d415d47518ec</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/78687707">EE Development Acceptance (master) - 1046 - 2024-11-26[20:44:21]</a></p><details><summary><strong>ci:test:security - 351 out of 358 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10758/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724311/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987139/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071312/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071311/">functional-tomcat90-mysql57/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036604/">functional-tomcat90-mysql57/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724310/">functional-tomcat90-mysql57/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036602/">functional-tomcat90-mysql57/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987137/">functional-tomcat90-mysql57/0/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133371/">functional-tomcat90-mysql57/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241472/">functional-tomcat90-mysql57/0/9</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030931/">functional-tomcat90-mysql57/0/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030930/">functional-tomcat90-mysql57/0/11</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096069/">functional-tomcat90-mysql57/0/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264822/">functional-tomcat90-mysql57/0/13</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981604/">functional-tomcat90-mysql57/0/14</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264821/">functional-tomcat90-mysql57/0/15</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071316/">functional-tomcat90-mysql57/0/16</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981605/">functional-tomcat90-mysql57/0/17</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264820/">functional-tomcat90-mysql57/0/18</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724316/">functional-tomcat90-mysql57/0/19</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031167/">functional-tomcat90-mysql57/0/20</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966067/">functional-tomcat90-mysql57/0/21</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133376/">functional-tomcat90-mysql57/0/22</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724314/">functional-tomcat90-mysql57/0/23</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987142/">functional-tomcat90-mysql57/0/24</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148726/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031162/">functional-tomcat90-mysql57/1/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031161/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148725/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148723/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148724/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148721/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148722/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031158/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031159/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264817/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031168/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071315/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030927/">functional-tomcat90-mysql57/1/13</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048374/">functional-tomcat90-mysql57/1/14</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966068/">functional-tomcat90-mysql57/1/15</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981602/">functional-tomcat90-mysql57/1/16</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724315/">functional-tomcat90-mysql57/1/17</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987143/">functional-tomcat90-mysql57/1/18</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030926/">functional-tomcat90-mysql57/1/19</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullreque [...]

2024-11-27 16:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10758/">test-portal-acceptance-pullrequest(master)#10758</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10758/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/79090787">[master] ci:test:security - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-27[06:23:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79090787<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/23862/">publish-testray-report#23862</a><br/></div></div>

2024-11-27 16:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 28 out of 29 jobs passed in 56 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f3bb3de3dbd03fc0211539a9b993df5515a5bef2">f3bb3de3dbd03fc0211539a9b993df5515a5bef2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d1f383ebee9055db957044f08bc289bd8a8131d7">d1f383ebee9055db957044f08bc289bd8a8131d7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/79052481">EE Development Acceptance (master) - 1047 - 2024-11-27[04:41:51]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 27 out of 29 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11847/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724335/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/465880/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/465881/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133408/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724336/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145087/">js-unit/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036631/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071337/">modules-compile/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031187/">modules-compile/0/1</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793937/">modules-compile/0/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030959/">modules-compile/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031186/">modules-compile/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048394/">modules-compile/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264859/">modules-compile/0/6</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966089/">modules-compile/0/7</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495389/">modules-compile/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096093/">modules-compile/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793936/">modules-compile/0/10</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/491989/">modules-compile/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036632/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030958/"><strike>modules-integration-mysql57/0/0</strike></a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966090/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096091/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145090/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987178/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987179/">playwright-js-tomcat90-mysql57/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133407/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981619/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11847/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at d1f383ebee9055db957044f08bc289bd8a8131d7:</strong></summary><ol><li><div><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030958//consoleText">modules-integration-mysql57/0/0</a><ol><li><details><summary><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030958/testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest">com.liferay.portal.remote.cors.client.test.AnnotationCORSClientTest</a> - <a>Failed 21 of last 21</a></summary><div><ol><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030958//testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest/testApplicationAnnotationCORSForGuestUser">testApplicationAnnotationCORSForGuestUser</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030958//testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest/testApplicationAnnotationCORSWithoutOAuth2">testApplicationAnnotationCORSWithoutOAuth2</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-11-27 16:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11847/">test-portal-acceptance-pullrequest(master)#11847</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11847/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/79191827">[master] ci:test:relevant - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-27[07:40:40]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79191827<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/25949/">publish-testray-report#25949</a><br/></div></div>

2024-11-27 17:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 349 out of 358 jobs passed in 1 hour 36 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1048">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1407401_11962</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f3bb3de3dbd03fc0211539a9b993df5515a5bef2">f3bb3de3dbd03fc0211539a9b993df5515a5bef2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d1f383ebee9055db957044f08bc289bd8a8131d7">d1f383ebee9055db957044f08bc289bd8a8131d7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/79052481">EE Development Acceptance (master) - 1047 - 2024-11-27[04:41:51]</a></p><details><summary><strong>ci:test:security - 349 out of 358 jobs PASSED</strong></summary><div><h4>9 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11962/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981623/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966093/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145094/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071340/">functional-tomcat90-mysql57/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036638/">functional-tomcat90-mysql57/0/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981622/">functional-tomcat90-mysql57/0/5</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793939/">functional-tomcat90-mysql57/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145093/">functional-tomcat90-mysql57/0/7</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/724339/">functional-tomcat90-mysql57/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241502/">functional-tomcat90-mysql57/0/9</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031196/">functional-tomcat90-mysql57/0/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030969/">functional-tomcat90-mysql57/0/11</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071346/">functional-tomcat90-mysql57/0/12</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048404/">functional-tomcat90-mysql57/0/13</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036642/">functional-tomcat90-mysql57/0/14</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148761/">functional-tomcat90-mysql57/0/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264871/">functional-tomcat90-mysql57/0/16</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1133420/">functional-tomcat90-mysql57/0/17</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071345/">functional-tomcat90-mysql57/0/18</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031195/">functional-tomcat90-mysql57/0/19</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048400/">functional-tomcat90-mysql57/0/20</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031191/">functional-tomcat90-mysql57/0/21</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793944/">functional-tomcat90-mysql57/0/22</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145098/">functional-tomcat90-mysql57/0/23</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241506/">functional-tomcat90-mysql57/0/24</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071338/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036636/">functional-tomcat90-mysql57/1/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148752/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241500/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241499/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036635/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096095/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1148751/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981620/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1096096/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793948/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264869/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030966/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1145100/">functional-tomcat90-mysql57/1/13</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1241508/">functional-tomcat90-mysql57/1/14</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/981628/">functional-tomcat90-mysql57/1/15</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966097/">functional-tomcat90-mysql57/1/16</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-dow [...]

2024-11-27 17:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11962/">test-portal-acceptance-pullrequest(master)#11962</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11962/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/79260819">[master] ci:test:security - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-27[07:40:40]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79260819<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26079/">publish-testray-report#26079</a><br/></div></div>

2024-11-27 23:41 UTC, rafaprax requested changes

2024-11-27 23:41 UTC, rafaprax commented on modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/ExtractedParameter.java
> +public class ExtractedParameter {
Hey @jgarcialr, Can you try to get rid of this class and use the  `MethodParameter` class directly? 

Thx

/cc @tomibiro

2024-11-27 23:49 UTC, rafaprax commented on modules/apps/portal-remote/portal-remote-json-web-service-web/src/main/java/com/liferay/portal/remote/json/web/service/web/internal/util/ExtractedParameter.java
> +public class ExtractedParameter {
Once you finish this change, I'll review the pr completely. 

Also, please add a unit test for the `MethodParameterExtractor#getMethodParameters`.

Thanks in advance

2024-11-28 19:48 UTC, tomibiro commented
Hi @rafaprax and @jgarcialr,
I added the unit tests.
Br, Tamas

2024-11-28 21:36 UTC, rafaprax commented
ci:test:sf

2024-11-28 21:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/8320/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8320/jenkins-report.html">here</a>.</b></p>

2024-11-28 21:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78652fdab0cb0da822283bee9b5e08bf39397e89">78652fdab0cb0da822283bee9b5e08bf39397e89</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-41375-i">LPD-41375-i</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/3bc9054755bfceed61aea286391d24c1925b8284">3bc9054755bfceed61aea286391d24c1925b8284</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/8320/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8320/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 9 formatting issues:
     [java] 1: Method "_mapGenerics" is unused: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractorTest.java 172 (Checkstyle:UnusedMethodCheck)
     [java] 2: Parameter "map" is unused: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractorTest.java 172 (Checkstyle:UnusedParameterCheck)
     [java] 3: Method "_stringWithGenerics" is unused: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractorTest.java 179 (Checkstyle:UnusedMethodCheck)
     [java] 4: Parameter "a" is unused: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractorTest.java 179 (Checkstyle:UnusedParameterCheck)
     [java] 5: Parameter "longList" is unused: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractorTest.java 179 (Checkstyle:UnusedParameterCheck)
     [java] 6: Method "_withPrimitives" is unused: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractorTest.java 183 (Checkstyle:UnusedMethodCheck)
     [java] 7: Parameter "a" is unused: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractorTest.java 183 (Checkstyle:UnusedParameterCheck)
     [java] 8: Parameter "b" is unused: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractorTest.java 183 (Checkstyle:UnusedParameterCheck)
     [java] 9: ./modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/util/MethodParameterExtractorTest.java expected:&lt;...opyrightText: (c) 20[24] Liferay, Inc. https...&gt; but was:&lt;...opyrightText: (c) 20[00] Liferay, Inc. https...&gt;
     [java] </pre></details></html>

2024-11-28 21:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/8320/">test-portal-source-format#8320</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8320/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/80360513">[master] ci:test:sf - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-28[13:36:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>80360513<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4694/">publish-testray-report#4694</a><br/></div></div>

2024-11-29 07:28 UTC, tomibiro commented
Hi @rafaprax and @jgarcialr,
The source formatter fails, because of some classes seem to be not used in the java test code. I think it is normal, because they are just only for the input Method type in the tests. If you have any solution to make it better please feel free to mention.
Thanks. Tamas

2024-11-29 10:39 UTC, jgarcialr commented
ci:test:sf

2024-11-29 10:39 UTC, jgarcialr commented
ci:test:relevant

2024-11-29 10:39 UTC, jgarcialr commented
ci:test:security

2024-11-29 10:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11526/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11526/jenkins-report.html">here</a>.</b></p>

2024-11-29 10:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6872/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6872/jenkins-report.html">here</a>.</b></p>

2024-11-29 10:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78652fdab0cb0da822283bee9b5e08bf39397e89">78652fdab0cb0da822283bee9b5e08bf39397e89</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-41375-i">LPD-41375-i</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/e8b8dcd98b0dd9ed42d307e67b7bd88f56f7009c">e8b8dcd98b0dd9ed42d307e67b7bd88f56f7009c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6872/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6872/jenkins-report.html">here</a>.</h5></details></html>

2024-11-29 10:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6872/">test-portal-source-format#6872</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6872/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/80657821">[master] ci:test:sf - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-29[02:39:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>80657821<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26155/">publish-testray-report#26155</a><br/></div></div>

2024-11-29 10:53 UTC, jgarcialr commented
ci:test:sf

2024-11-29 10:53 UTC, jgarcialr commented
ci:test:relevant

2024-11-29 10:53 UTC, jgarcialr commented
ci:test:security

2024-11-29 10:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13174/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13174/jenkins-report.html">here</a>.</b></p>

2024-11-29 10:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>security</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11996/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11996/jenkins-report.html">here</a>.</b></p>

2024-11-29 10:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10737/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10737/jenkins-report.html">here</a>.</b></p>

2024-11-29 10:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78652fdab0cb0da822283bee9b5e08bf39397e89">78652fdab0cb0da822283bee9b5e08bf39397e89</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liferay-appsec/liferay-portal/tree/LPD-41375-i">LPD-41375-i</a><br/>Branch GIT ID: <a href="https://github.com/liferay-appsec/liferay-portal/commit/d6e24910ce53260557dd739b58168bff1e21ae7c">d6e24910ce53260557dd739b58168bff1e21ae7c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10737/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10737/jenkins-report.html">here</a>.</h5></details></html>

2024-11-29 10:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10737/">test-portal-source-format#10737</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10737/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/80658448">[master] ci:test:sf - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-29[02:53:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>80658448<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/40880/">publish-testray-report#40880</a><br/></div></div>

2024-11-29 11:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 28 out of 29 jobs passed in 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78652fdab0cb0da822283bee9b5e08bf39397e89">78652fdab0cb0da822283bee9b5e08bf39397e89</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78652fdab0cb0da822283bee9b5e08bf39397e89">78652fdab0cb0da822283bee9b5e08bf39397e89</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/80021315">EE Development Acceptance (master) - 1051 - 2024-11-28[04:38:00]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 27 out of 29 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13174/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031945/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1072299/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1134551/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032008/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1072301/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988209/">js-unit/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031965/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037755/">modules-compile/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725130/">modules-compile/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988274/">modules-compile/0/2</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982369/">modules-compile/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725128/">modules-compile/0/4</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242377/">modules-compile/0/5</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032007/">modules-compile/0/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037753/">modules-compile/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037754/">modules-compile/0/8</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988273/">modules-compile/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1072300/">modules-compile/0/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1146094/">modules-compile/0/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725129/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266199/"><strike>modules-integration-mysql57/0/0</strike></a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242378/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1149527/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1146093/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725127/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266201/">playwright-js-tomcat90-mysql57/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988272/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266200/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13174/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 78652fdab0cb0da822283bee9b5e08bf39397e89:</strong></summary><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266199//consoleText">modules-integration-mysql57/0/0</a><ol><li><details><summary><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266199/testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest">com.liferay.portal.remote.cors.client.test.AnnotationCORSClientTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/80206558/history">Failed 24 of last 24</a></summary><div><ol><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266199//testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest/testApplicationAnnotationCORSForGuestUser">testApplicationAnnotationCORSForGuestUser</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266199//testReport/com.liferay.portal.remote.cors.client.test/AnnotationCORSClientTest/testApplicationAnnotationCORSWithoutOAuth2">testApplicationAnnotationCORSWithoutOAuth2</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-11-29 11:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/13174/">test-portal-acceptance-pullrequest(master)#13174</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13174/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/80702121">[master] ci:test:relevant - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-29[02:53:29]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>80702121<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28799/">publish-testray-report#28799</a><br/></div></div>

2024-11-29 12:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 351 out of 358 jobs passed in 1 hour 30 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78652fdab0cb0da822283bee9b5e08bf39397e89">78652fdab0cb0da822283bee9b5e08bf39397e89</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78652fdab0cb0da822283bee9b5e08bf39397e89">78652fdab0cb0da822283bee9b5e08bf39397e89</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/80021315">EE Development Acceptance (master) - 1051 - 2024-11-28[04:38:00]</a></p><details><summary><strong>ci:test:security - 351 out of 358 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11916/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1097071/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982355/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988263/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037738/">functional-tomcat90-mysql57/0/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988262/">functional-tomcat90-mysql57/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032016/">functional-tomcat90-mysql57/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988261/">functional-tomcat90-mysql57/0/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725108/">functional-tomcat90-mysql57/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266176/">functional-tomcat90-mysql57/0/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031993/">functional-tomcat90-mysql57/0/9</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032022/">functional-tomcat90-mysql57/0/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1134539/">functional-tomcat90-mysql57/0/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725115/">functional-tomcat90-mysql57/0/12</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242372/">functional-tomcat90-mysql57/0/13</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266186/">functional-tomcat90-mysql57/0/14</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266185/">functional-tomcat90-mysql57/0/15</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032021/">functional-tomcat90-mysql57/0/16</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037745/">functional-tomcat90-mysql57/0/17</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1097077/">functional-tomcat90-mysql57/0/18</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725114/">functional-tomcat90-mysql57/0/19</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1134534/">functional-tomcat90-mysql57/0/20</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795205/">functional-tomcat90-mysql57/0/21</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1097075/">functional-tomcat90-mysql57/0/22</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725112/">functional-tomcat90-mysql57/0/23</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266181/">functional-tomcat90-mysql57/0/24</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982353/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031992/">functional-tomcat90-mysql57/1/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049194/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242363/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988259/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795203/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242362/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725106/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1134529/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982352/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242368/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/967133/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032019/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1146083/">functional-tomcat90-mysql57/1/13</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988266/">functional-tomcat90-mysql57/1/14</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1134535/">functional-tomcat90-mysql57/1/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266182/">functional-tomcat90-mysql57/1/16</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037743/">functional-tomcat90-mysql57/1/17</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725113/">functional-tomcat90-mysql57/1/18</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795207/">functional-tomcat90-mysql57/1/19</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-d [...]

2024-11-29 12:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11916/">test-portal-acceptance-pullrequest(master)#11916</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11916/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/80711531">[master] ci:test:security - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-29[02:39:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>80711531<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/25756/">publish-testray-report#25756</a><br/></div></div>

2024-11-29 12:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11526/">test-portal-acceptance-pullrequest(master)#11526</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11526/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/80711636">[master] ci:test:relevant - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-29[02:39:43]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>80711636<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/23823/">publish-testray-report#23823</a><br/></div></div>

2024-11-29 13:00 UTC, jgarcialr commented
ci:test:relevant

2024-11-29 13:28 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:security - 351 out of 358 jobs passed in 2 hours 34 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78652fdab0cb0da822283bee9b5e08bf39397e89">78652fdab0cb0da822283bee9b5e08bf39397e89</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/78652fdab0cb0da822283bee9b5e08bf39397e89">78652fdab0cb0da822283bee9b5e08bf39397e89</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/80021315">EE Development Acceptance (master) - 1051 - 2024-11-28[04:38:00]</a></p><details><summary><strong>ci:test:security - 351 out of 358 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11996/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/967154/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982371/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266204/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/967155/">functional-tomcat90-mysql57/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037760/">functional-tomcat90-mysql57/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032033/">functional-tomcat90-mysql57/0/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/967149/">functional-tomcat90-mysql57/0/6</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795220/">functional-tomcat90-mysql57/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037759/">functional-tomcat90-mysql57/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1097093/">functional-tomcat90-mysql57/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795229/">functional-tomcat90-mysql57/0/10</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1097104/">functional-tomcat90-mysql57/0/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1149599/">functional-tomcat90-mysql57/0/12</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037769/">functional-tomcat90-mysql57/0/13</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1149598/">functional-tomcat90-mysql57/0/14</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1097103/">functional-tomcat90-mysql57/0/15</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1134567/">functional-tomcat90-mysql57/0/16</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/967162/">functional-tomcat90-mysql57/0/17</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049215/">functional-tomcat90-mysql57/0/18</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1072309/">functional-tomcat90-mysql57/0/19</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725134/">functional-tomcat90-mysql57/0/20</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1134562/">functional-tomcat90-mysql57/0/21</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266207/">functional-tomcat90-mysql57/0/22</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049212/">functional-tomcat90-mysql57/0/23</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032016/">functional-tomcat90-mysql57/0/24</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795217/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032031/">functional-tomcat90-mysql57/1/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242380/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266202/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032009/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1149589/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1097088/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795215/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037756/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049206/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988283/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1072306/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/725135/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1266209/">functional-tomcat90-mysql57/1/13</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032040/">functional-tomcat90-mysql57/1/14</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242386/">functional-tomcat90-mysql57/1/15</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049213/">functional-tomcat90-mysql57/1/16</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242387/">functional-tomcat90-mysql57/1/17</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1037764/">functional-tomcat90-mysql57/1/18</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/982375/">functional-tomcat90-mysql57/1/19</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullreq [...]

2024-11-29 13:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11996/">test-portal-acceptance-pullrequest(master)#11996</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11996/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>security<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-appsec/liferay-portal/pull/2089">liferay-appsec#2089</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/80734382">[master] ci:test:security - liferay-appsec &gt; liferay-appsec - PR#2089 - 2024-11-29[02:53:35]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>80734382<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26163/">publish-testray-report#26163</a><br/></div></div>

2024-11-29 13:53 UTC, jgarcialr commented
Waiting on latest result of ci:test:relevant, as previous commit before the force-push had a typo that prevents compilation of some JSONWebServiceTests

2024-11-29 21:21 UTC, rafaprax commented
resent here https://github.com/liferay-appsec/liferay-portal/pull/2095

2024-11-29 21:21 UTC, rafaprax commented
ci:close

2024-11-29 21:21 UTC, closed without merging